name: memory
description: memory description
events: {}
structs: {}
typedefs: {}
state:
    owner: AgentID # current owner of this smart contract
funcs:
    f:
        params:
            n: Uint32
views: {}
