name: CoreGovernance
description: Governance contract
structs: {}
typedefs: {} 
state: {}
funcs:
  # state controller
  rotateStateController:
    params:
      stateControllerAddress=S: Address
  addAllowedStateControllerAddress:
    params:
      stateControllerAddress=S: Address
  removeAllowedStateControllerAddress:
    params:
      stateControllerAddress=S: Address
  # chain owner
  claimChainOwnership: {}
  delegateChainOwnership:
    params:
      chainOwner=c: AgentID
  # fees
  setFeePolicy:
    params:
      feePolicyBytes=d: Bytes
  # chain info
  setChainInfo:
    params:
      maxBlobSize=g: Uint32? # default maximum size of a blob
      maxEventSize=h: Uint16? # default maximum size of a single event
      maxEventsPerReq=i: Uint16? # default maximum number of events per request
  # access nodes
  addCandidateNode:
    params:
      accessNodeInfoPubKey=m: Bytes
      accessNodeInfoCertificate=n: Bytes
      accessNodeInfoForCommittee=l: Bool
      accessNodeInfoAccessAPI=o: String
  revokeAccessNode:
    params:
      accessNodeInfoPubKey=m: Bytes
      accessNodeInfoCertificate=n: Bytes
  changeAccessNodes:
    params:
      changeAccessNodesActions=p: map[Bytes]Uint8

views:
  # state controller
  getAllowedStateControllerAddresses:
    results:
      allowedStateControllerAddresses=b: Address[] # native contract, so this is an Array16
  # chain owner
  getChainOwner:
    results:
      chainOwner=c: AgentID
  # fees
  getFeePolicy:
    results:
      feePolicyBytes=d: Bytes
  # chain info
  getChainInfo:
    results:
      chainID=c: ChainID
      chainOwnerID=o: AgentID
      description=d: String
      gasFeePolicyBytes=g: Bytes
      maxBlobSize=mb: Uint32
      maxEventSize=me: Uint16
      maxEventsPerReq=mr: Uint16
  getMaxBlobSize:
    results:
      maxBlobSize=mb: Uint32
  # access nodes
  getChainNodes:
    results:
      accessNodeCandidates=ac: map[Bytes]Bytes
      accessNodes=an: map[Bytes]Bytes
