name: WasmRequests
description: WasmLib request structures
events: {}
structs:
  CallRequest:
    contract: Hname
    function: Hname
    params: Bytes
    allowance: Bytes # caller assets that the call is allowed to access

  DeployRequest:
    progHash: Hash
    name: String
    description: String
    params: Bytes

  PostRequest:
    chainID: ChainID
    contract: Hname
    function: Hname
    params: Bytes
    allowance: Bytes # caller assets that the call is allowed to access
    transfer: Bytes # assets that are transferred into caller account
    delay: Uint32

  SendRequest:
    address: Address
    transfer: Bytes

  TransferRequest:
    agentID: AgentID
    create: Bool
    transfer: Bytes

typedefs: {}
state: {}
funcs: {}
views: {}
